### ISSUE TITLE
OpenShift deployment is broken

### ISSUE THREAD

**Issue by pmonks** [finos-fdx/bot-github-chatops#49]
### Steps to Reproduce:
 1. Trigger a Travis CI build (e.g. make a commit)

### Expected Result:
The JDK8 job on Travis CI deploys the updated JARs to OpenShift, running against the `foundation-dev` pod.

### Actual Result:
The [JDK8 job fails](https://travis-ci.org/finos-fdx/bot-github-chatops/jobs/421258431#L916) with the message: `error: error processing the template "bot-github-chatops-template": processedtemplates is forbidden: User "maoo-1" cannot create processedtemplates in the namespace "ssf-dev": User "maoo-1" cannot create processedtemplates in project "ssf-dev"`

**Comment by pmonks** [comment]
@maoo any updates on this?  This [issue is still occurring](https://travis-ci.org/finos-fdx/bot-github-chatops/jobs/428792695#L915).

**Comment by maoo** [comment]
Fixed! https://travis-ci.org/finos-fdx/bot-github-chatops/jobs/428795470
