### ISSUE TITLE
Reinstate OC_TOKEN in .travis.yml 

### ISSUE THREAD

**Issue by pmonks** [finos-fdx/bot-github-chatops#50]
The (encrypted) OC_TOKEN setting was removed from `.travis.yml` in commit 19bb498c7b29342a0d53a9a26ba595b12d69e10b.  Whether this was by accident or intentional, it needs to be reinstated in `.travis.yml` (and removed from the Travis UI settings, if it has been configured there), as it's best practice to explicitly store and manage CI settings in the git repository itself (i.e. in the `.travis.yml` file), rather than as "magic" settings buried in the Travis UI that some of the project's developers may not have access to.

**Comment by maoo** [comment]
Fixed on https://github.com/finos-fdx/bot-github-chatops/commit/e4fb53d7e27cbd7fdbe193bcf0e284d02aa20602
