### ISSUE TITLE
Whitesource plug-in should not be run on every branch, since Whitesource is not branch aware

### ISSUE THREAD

**Issue by pmonks** [finos-fdx/bot-github-chatops#57]
In a recent PR, the [Whitesource plug-in was configured to run on every branch](
https://github.com/finos-fdx/bot-github-chatops/blob/master/.travis.yml#L48).  This is problematic because Whitesource only supports one analysis / report per GitHub repository, so configuring it on every branch means that that analysis will be for a non-deterministic branch (i.e. whichever branch was last committed to). Worse, the analysis could be run on temporary or experimental branches that get rejected and are never merged into the final codebase.

This is highly problematic as potential consumers of the project who choose review the Whitesource report to help determine the project's quality may come away with a grossly inaccurate understanding based on in-progress or experimental development work.

Until such time as Whitesource supports per-branch reports, the only viable workaround is to pick a single, well-defined branch for the Whitesource analysis to run against, and in the case of bot-github-chatops, the only branch that makes sense is master (since it’s the branch that represents the current production version of the code).

Note: this was originally how Whitesource had been deliberately and consciously configured for this project.  It’s not at all clear to me why this regression was introduced in the recent PR.

**Comment by maoo** [comment]
Thanks @pmonks , I reverted the change on dev.

The reason for the change was to test WhiteSource as a tool to spot security and licensing issues earlier in the development process, hence enabling it on the dev branch.

Please note that Travis syntax is a bit misleading; when it says
```
all_branches: true
condition: $TRAVIS_BRANCH -eq "master" || $TRAVIS_BRANCH -eq "dev"
```
it means that it will run only on `master` and `dev` branches.

The change is now reverted to `branch: master`.

**Comment by pmonks** [comment]
@maoo yes being able to see the results of a Whitesource scan earlier in the development workflow would be beneficial for the *project team*, however given how the Whitesource product functions right now, that would be deleterious for *project consumers*, and I think that's the wrong trade off to make (at least for FINOS projects).

Perhaps you could follow up with your Whitesource contacts, to see if per-branch analysis & reporting is on their roadmap?  That's the only way to meet the needs of both constituencies.
